### ISSUE TITLE
Attempts to access undefined response property

### ISSUE THREAD

**Issue by sarus** [polarityio/fullcontact#1]
```
{
    "debug": {
        "stderr": "\nMessage: Cannot read property 'message' of undefined\n\nStacktrace:\n====================\nTypeError: Cannot read property 'message' of undefined\n    at results.forEach.result (/app/polarity-server/integrations/fullcontact/integration.js:100:35)\n    at Array.forEach (native)\n    at async.parallelLimit (/app/polarity-server/integrations/fullcontact/integration.js:94:17)\n    at /app/polarity-server/node_modules/async/dist/async.js:3861:9\n    at /app/polarity-server/node_modules/async/dist/async.js:421:16\n    at iterateeCallback (/app/polarity-server/node_modules/async/dist/async.js:928:24)\n    at /app/polarity-server/node_modules/async/dist/async.js:906:16\n    at /app/polarity-server/node_modules/async/dist/async.js:3858:13\n    at Request._callback (/app/polarity-server/integrations/fullcontact/integration.js:81:21)\n    at Request.self.callback (/app/polarity-server/node_modules/request/request.js:186:22)\n\n"
    },
    "md5": "baa19b255c33f523fede006988c3ae7a"
}
```

**Comment by radar989** [comment]
solved with updated to new API
